version: '3'
services:
  mysql:
#    image: mysql:5.7
    image: mariadb:10.3
    container_name: mariadb
    restart: always
    expose:
      - 3306
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=toor
      - MYSQL_DATABASE=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=toor
#    volumes:
#      - dbdata:/var/lib/mysql
#      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
      
  node-app:
    build: .
    container_name: node-app
    links:
      - mysql
    ports:
      - "3005:3005"